name: pdf_generation

on:
  push:
    branches:
     - master

jobs:
  GeneratePdfArtifacts:
    name: Generate PDFs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Generate Full PDF Template      
        uses: ./
        with:        

          # The latex template to use (defaults to one here)
          latex_template: resume.tex

          # One of "minimal" or "pdf" for the template with image, etc.
          pdf_type: pdf

          # A variables file to use
          variables_file: templates/joss-variables.txt
 
          # A mapping file to use
          mapping_file: templates/joss-mapping.txt

      - name: Upload full templated pdf as artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: full-pdf
          path: Akash_Resume.pdf
