 # See https://github.com/rseng/pdf-generator for release
 - name: Generate Full PDF Template      
   uses: rseng/pdf-generator@master
   with:        

     # The latex template to use (defaults to one here)
     latex_template: templates/latex.template.joss

     # The markdown file to render,path is relative to repository
     # make sure that images are also relative to the root in the file
     paper_markdown: paper/paper.md

     # The paper pdf to save
     paper_outfile: paper.pdf

     # Bibliography file, if existing
     bibtex: paper/paper.bib

     # A path to a png logo file
     png_logo: paper/sorse.png

     # One of "minimal" or "pdf" for the template with image, etc.
     pdf_type: pdf

     # A variables file to use
     variables_file: templates/joss-variables.txt
 
     # A mapping file to use
     mapping_file: templates/joss-mapping.txt