name: pdf_generation

on:
  push:
    branches:
     - master

jobs:
  GeneratePdfArtifacts:
    name: Generate PDFs
    runs-on: ubuntu-latest
    steps:
      - name: PDFlatex
        # You may pin to the exact commit or the version.
        # uses: Closoco/pdflatex-action@27af51efacd7fe7d86953532c432f0e514c5cf4e
        uses: Closoco/pdflatex-action@v1.1.0
        with:
          # name of the tex file
          texFile: resume.tex
